version: "3"
services:
  postgresql:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
#      POSTGRES_DB: se
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    networks:
      - my-network
  seboard:
    image: maanjong/se-dev:seboard
    container_name: seboard
    ports:
      - "8080:8080"
    networks:
      - my-network
  nginx:
    image: maanjong/se-dev:nginx
    container_name: nginx
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
