version: "3"
services:
  postgresql:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
#      POSTGRES_DB: se
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    networks:
      my-network:
        ipv4_address: 172.19.0.2

  seboard:
    image: maanjong/se-dev:seboard
    container_name: seboard
    ports:
      - "8080:8080"
    networks:
      my-network:
        ipv4_address: 172.19.0.3

  nginx:
    image: maanjong/se-dev:nginx
    container_name: nginx
    networks:
      my-network:
        ipv4_address: 172.19.0.4
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      my-network:
        ipv4_address: 172.19.0.5

networks:
  my-network:
    ipam:
      driver: bridge
      config:
        - subnet: 172.19.0.0/24
