server:
  port: 8081


spring:
  servlet:
    multipart:
      enabled: true
      location: /Users/manjong/
      max-request-size: 30MB
      max-file-size: 10MB
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
file:
  dir:

