

spring:
  security:
    oauth2:
      client: ## 클라이언트 설정
        registration:
          keycloak:
            authorization-grant-type : authorization_code                         # OAuth 2.0 권한 부여 타입
            client-id : oauth2-client-app                                         # 서비스 공급자에 등록된 클라이언트 아이디
            client-name : oauth2-client-app                                       # 클라이언트 이름
            client-secret : do5BSCutto0Lreb3uxjGh3Ga1gdj4IZ9                      # 서비스 공급자에 등록된 클라이언트 비밀번호
            redirect-uri : http://localhost:8081/login/oauth2/code/keycloak       # 인가서버에서 권한 코드 부여 후 클라이언트로 리다이렉트하는 위치
            client-authentication-method: client_secret_basic                        # 클라이언트 자격증명 전송 방식, basic = Base64Encoding(client-id + client-secret)
            scope: openid,profile,email                                                   # 리소스에 접근 제한 범위

          google:
            client-id: 52614953019-qc55m23qnlrb3788vaf4ds4joqqmi89m.apps.googleusercontent.com
            client-secret: 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
            scope: openid,profile,email

          naver:
            client-id: XjoXCP7jevwVzoWUnTXh
            client-secret: ubujedg3Fc
            authorization-grant-type: authorization_code
            client-name: naver-client-app
            redirect-uri: http://localhost:8081/login/oauth2/code/naver
            scope: profile,email

        provider: ## 공급자 설정
          keycloak:
            authorization-uri: http://localhost:8080/realms/oauth2/protocol/openid-connect/auth # OAuth 2.0 권한 코드 부여 엔드포인트
            issuer-uri: http://localhost:8080/realms/oauth2                                     # 서비스 공급자의 위치
            jwk-set-uri: http://localhost:8080/realms/oauth2/protocol/openid-connect/certs      # OAuth 2.0 JwkSetUri 엔드 포인트
            token-uri: http://localhost:8080/realms/oauth2/protocol/openid-connect/token        # OAuth 2.0 토큰 엔드 포인트
            user-info-uri: http://localhost:8080/realms/oauth2/protocol/openid-connect/userinfo # OAuth 2.0 UserInfo 엔드 포인트
            user-name-attribute: preferred_username                                             # OAuth 2.0 사용자명을 추출하는 클레임명
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          ## 구글은 default로 설정되어 있음